services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      ADDRESS_HEADER: X-Forwarded-For
      XFF_DEPTH: 1
    env_file:
      - .env
    ports:
      - "3002:3000"
