version: "0.2"
ignorePaths:
  - .gitignore
  - src/routes/layout.css
dictionaryDefinitions: []
dictionaries: []
words:
  - Antunes
  - arcticons
  - Ferreira
  - iconify
  - Vitor
ignoreWords: []
import: []
