version: "0.2"
ignorePaths:
  - .gitignore
  - src/routes/layout.css
  - .env
  - .example.env
  - .dockerignore
  - Dockerfile
  - compose.yaml
  - nginx.conf.template
dictionaryDefinitions: []
dictionaries: []
words:
  - arcticons
  - boxicons
  - cema
  - Goback
  - iconify
  - nesf
  - neuro
  - NEUROPSYCHOLOGIST
  - renata
ignoreWords: []
import: []
