version: "0.2"
ignorePaths:
  - .gitignore
  - src/routes/layout.css
  - .env
  - .example.env
dictionaryDefinitions: []
dictionaries: []
words:
  - arcticons
  - boxicons
  - cema
  - iconify
  - nesf
  - neuro
  - NEUROPSYCHOLOGIST
  - renata
ignoreWords: []
import: []
